[2022-09-13 20:16:42,375] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: test_dag.notify scheduled__2022-09-11T00:00:00+00:00 [queued]>
[2022-09-13 20:16:42,387] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: test_dag.notify scheduled__2022-09-11T00:00:00+00:00 [queued]>
[2022-09-13 20:16:42,389] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2022-09-13 20:16:42,390] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2022-09-13 20:16:42,392] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2022-09-13 20:16:42,429] {taskinstance.py:1377} INFO - Executing <Task(BashOperator): notify> on 2022-09-11 00:00:00+00:00
[2022-09-13 20:16:42,436] {standard_task_runner.py:52} INFO - Started process 228 to run task
[2022-09-13 20:16:42,462] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'test_dag', 'notify', 'scheduled__2022-09-11T00:00:00+00:00', '--job-id', '22', '--raw', '--subdir', 'DAGS_FOLDER/pre_parser.py', '--cfg-path', '/tmp/tmpwzyonr4i', '--error-file', '/tmp/tmp1nqz58xk']
[2022-09-13 20:16:42,465] {standard_task_runner.py:80} INFO - Job 22: Subtask notify
[2022-09-13 20:16:42,596] {task_command.py:369} INFO - Running <TaskInstance: test_dag.notify scheduled__2022-09-11T00:00:00+00:00 [running]> on host 5d92941617fc
[2022-09-13 20:16:42,926] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=test_dag
AIRFLOW_CTX_TASK_ID=notify
AIRFLOW_CTX_EXECUTION_DATE=2022-09-11T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-09-11T00:00:00+00:00
[2022-09-13 20:16:42,931] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2022-09-13 20:16:42,934] {subprocess.py:74} INFO - Running command: ['bash', '-c', 'echo "Hello!"']
[2022-09-13 20:16:42,971] {subprocess.py:85} INFO - Output:
[2022-09-13 20:16:42,977] {subprocess.py:92} INFO - Hello!
[2022-09-13 20:16:42,979] {subprocess.py:96} INFO - Command exited with return code 0
[2022-09-13 20:16:43,055] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=test_dag, task_id=notify, execution_date=20220911T000000, start_date=20220913T201642, end_date=20220913T201643
[2022-09-13 20:16:43,163] {local_task_job.py:156} INFO - Task exited with return code 0
[2022-09-13 20:16:43,289] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
