[2022-09-14 18:48:36,891] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: parser_dag.parser_python manual__2022-09-14T18:47:23.846238+00:00 [queued]>
[2022-09-14 18:48:36,907] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: parser_dag.parser_python manual__2022-09-14T18:47:23.846238+00:00 [queued]>
[2022-09-14 18:48:36,909] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2022-09-14 18:48:36,910] {taskinstance.py:1357} INFO - Starting attempt 2 of 2
[2022-09-14 18:48:36,911] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2022-09-14 18:48:36,934] {taskinstance.py:1377} INFO - Executing <Task(PythonOperator): parser_python> on 2022-09-14 18:47:23.846238+00:00
[2022-09-14 18:48:36,944] {standard_task_runner.py:52} INFO - Started process 7117 to run task
[2022-09-14 18:48:36,971] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'parser_dag', 'parser_python', 'manual__2022-09-14T18:47:23.846238+00:00', '--job-id', '85', '--raw', '--subdir', 'DAGS_FOLDER/pre_parser.py', '--cfg-path', '/tmp/tmpcpt4m4_r', '--error-file', '/tmp/tmp_v1g2dwq']
[2022-09-14 18:48:36,974] {standard_task_runner.py:80} INFO - Job 85: Subtask parser_python
[2022-09-14 18:48:37,105] {task_command.py:369} INFO - Running <TaskInstance: parser_dag.parser_python manual__2022-09-14T18:47:23.846238+00:00 [running]> on host 1085bb4029c2
[2022-09-14 18:48:37,203] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=parser_dag
AIRFLOW_CTX_TASK_ID=parser_python
AIRFLOW_CTX_EXECUTION_DATE=2022-09-14T18:47:23.846238+00:00
AIRFLOW_CTX_TRY_NUMBER=2
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-09-14T18:47:23.846238+00:00
[2022-09-14 18:48:50,250] {logging_mixin.py:115} INFO - No more products in 5ka
[2022-09-14 18:49:01,449] {logging_mixin.py:115} INFO - No more products in magnit-univer
[2022-09-14 18:49:13,144] {logging_mixin.py:115} INFO - No more products in perekrestok
[2022-09-14 18:49:22,526] {logging_mixin.py:115} INFO - No more products in dixy
[2022-09-14 18:49:35,245] {logging_mixin.py:115} INFO - No more products in lenta-super
[2022-09-14 18:49:46,831] {logging_mixin.py:115} INFO - No more products in vkusvill_offline
[2022-09-14 18:49:58,171] {logging_mixin.py:115} INFO - No more products in mgnl
[2022-09-14 18:49:58,324] {logging_mixin.py:115} INFO - No data for azbuka_vkusa
[2022-09-14 18:49:58,329] {taskinstance.py:1889} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 171, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 189, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/pre_parser.py", line 99, in final
    with open(posixpath.join(home_path, "prices.pickle"), "w") as handle:
NameError: name 'posixpath' is not defined
[2022-09-14 18:49:58,357] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=parser_dag, task_id=parser_python, execution_date=20220914T184723, start_date=20220914T184836, end_date=20220914T184958
[2022-09-14 18:49:58,374] {standard_task_runner.py:97} ERROR - Failed to execute job 85 for task parser_python (name 'posixpath' is not defined; 7117)
[2022-09-14 18:49:58,417] {local_task_job.py:156} INFO - Task exited with return code 1
[2022-09-14 18:49:58,448] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
